### ISSUE TITLE
No offset applied in conversion to and from Kelvin

### ISSUE THREAD

**Issue by zaript** [numbas/numbas-extension-quantities#9]
To reproduce, try creating JME variable

`string(qty(-40, "degC") in "degK")`

This will return "40 K" instead of "233.15 K".

**Comment by christianp** [comment]
This looks like a bug in the library we use, js-quantities. The first issue in their issue tracker (gentooboontoo/js-quantities#1) is about this, and it's closed, but the conversion is wrong now - maybe they rewrote it since then?
I'll do some digging to see if it's possible for me to fix it.

**Comment by christianp** [comment]
Actually, I think that js-quantities might have decided to interpret `degC` and `degK` as meaning _differences_ in temperature.

I found out a while ago that these kinds of things are called 'torsors' - two measurements have a well-defined difference, but no absolute value. You have the same problem with times - the difference between two dates isn't a date, it's an interval.

So I wonder if the developers of js-quantities just decided to only treat differences in temperature, to avoid confusion between the two meanings.

I think you'll have to apply the offset yourself.

**Comment by zaript** [comment]
Many thanks @christianp,

It just dawned on me, that the degK and tempK are not the same thing! One is the difference, and another is the absolute value. Perhaps, hint could be added in the documentation to this extension, in case the user acts like me and does not always look into the underlying library docs.
